providers:
  - name: 奈云
    proxy: false
    path: https://naiyun0315.xn--8stx8olrwkucjq3b.com/api/v1/client/subscribe?token=745f0f059c5256cf9b2e4cc4fc87ee81
    remote: true
  - name: 一元
    proxy: true
    path: https://sub2.smallstrawberry.com/api/v1/client/subscribe?token=01b5b92d76a64a1bbe331c77c53e818a
    remote: true
  - name: 一元机场
    proxy: false
    path: C:/Users/Lenovo/Desktop/config/一元.yaml
    remote: false
rulesets:
  - type: remote
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/sing/geo/geoip/cn.srs
    format: binary
    tag: china-ip
    download_detour: select
    update_interval: 1d
    label: china
    china: true
  - type: remote
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/sing/geo/geosite/cn.srs
    format: binary
    tag: china-site
    download_detour: select
    update_interval: 1d
    label: china
    china: true
    dnsRule: internal
  - type: remote
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/sing/geo/geosite/youtube.srs
    format: binary
    tag: youtube
    download_detour: select
    update_interval: 1d
    china: false
    dnsRule: external
  - type: local
    path: /opt/singbox/openai.srs
    format: binary
    tag: openai
    china: false
    dnsRule: external
